CREATE TABLE slides (id INT AUTO_INCREMENT NOT NULL, correousel_id INT NOT NULL, linkImagem VARCHAR(255) NOT NULL, texto LONGTEXT NOT NULL, ordem INT DEFAULT NULL, titulo VARCHAR(255) DEFAULT NULL, redirect VARCHAR(255) DEFAULT NULL, INDEX IDX_B8C020912782E747 (correousel_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE empresas (id INT AUTO_INCREMENT NOT NULL, album_id INT DEFAULT NULL, nome VARCHAR(255) NOT NULL, historia LONGTEXT NOT NULL, resumo LONGTEXT NOT NULL, missao LONGTEXT NOT NULL, visao LONGTEXT NOT NULL, valores LONGTEXT NOT NULL, slogan LONGTEXT DEFAULT NULL, dominio VARCHAR(255) NOT NULL, urlLogo VARCHAR(255) DEFAULT NULL, iframeGoogleMaps LONGTEXT DEFAULT NULL, endereco VARCHAR(255) NOT NULL, telefone VARCHAR(255) DEFAULT NULL, emailContato VARCHAR(255) NOT NULL, idGoogleAnalytics VARCHAR(255) DEFAULT NULL, nomeTema VARCHAR(255) NOT NULL, temaDark TINYINT(1) NOT NULL, nomeCorTema VARCHAR(255) DEFAULT NULL, temaFullWidth TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_70DD49A51137ABCF (album_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE empresas_detalhes (empresa_id INT NOT NULL, detalhe_id INT NOT NULL, INDEX IDX_4D495A46521E1991 (empresa_id), INDEX IDX_4D495A466B253812 (detalhe_id), PRIMARY KEY(empresa_id, detalhe_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE carrousels (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE paginas (id INT AUTO_INCREMENT NOT NULL, album_id INT DEFAULT NULL, titulo VARCHAR(255) NOT NULL, nomeMenu VARCHAR(255) NOT NULL, conteudo LONGTEXT NOT NULL, tags LONGTEXT DEFAULT NULL, resumo LONGTEXT DEFAULT NULL, ordem INT NOT NULL, publicar TINYINT(1) NOT NULL, postagem TINYINT(1) NOT NULL, dataHora DATETIME NOT NULL, UNIQUE INDEX UNIQ_28335C341137ABCF (album_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE imagens (id INT AUTO_INCREMENT NOT NULL, album_id INT DEFAULT NULL, url VARCHAR(255) NOT NULL, thumbnail VARCHAR(255) NOT NULL, capa TINYINT(1) NOT NULL, absolutePath VARCHAR(255) NOT NULL, INDEX IDX_49E534EF1137ABCF (album_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE tentativas_login (id INT AUTO_INCREMENT NOT NULL, time DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE produtos (id INT AUTO_INCREMENT NOT NULL, album_id INT DEFAULT NULL, nome VARCHAR(255) NOT NULL, conteudo LONGTEXT NOT NULL, tags LONGTEXT DEFAULT NULL, resumo LONGTEXT NOT NULL, destaque TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_3E524351137ABCF (album_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE produtos_detalhes (produto_id INT NOT NULL, detalhe_id INT NOT NULL, INDEX IDX_DA083948105CFD56 (produto_id), INDEX IDX_DA0839486B253812 (detalhe_id), PRIMARY KEY(produto_id, detalhe_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE parceiros (id INT AUTO_INCREMENT NOT NULL, album_id INT DEFAULT NULL, nome VARCHAR(255) NOT NULL, url VARCHAR(255) DEFAULT NULL, slogan VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_949C60CC1137ABCF (album_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE sessoes (id INT AUTO_INCREMENT NOT NULL, codigo VARCHAR(255) NOT NULL, conteudo LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE albuns (id INT AUTO_INCREMENT NOT NULL, nome VARCHAR(255) NOT NULL, descricao VARCHAR(255) DEFAULT NULL, publicar TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE credenciais (id INT AUTO_INCREMENT NOT NULL, login VARCHAR(255) NOT NULL, senha VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, salt VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE detalhes (id INT AUTO_INCREMENT NOT NULL, `label` VARCHAR(255) NOT NULL, conteudo LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE slides ADD CONSTRAINT FK_B8C020912782E747 FOREIGN KEY (correousel_id) REFERENCES carrousels (id);
ALTER TABLE empresas ADD CONSTRAINT FK_70DD49A51137ABCF FOREIGN KEY (album_id) REFERENCES albuns (id);
ALTER TABLE empresas_detalhes ADD CONSTRAINT FK_4D495A46521E1991 FOREIGN KEY (empresa_id) REFERENCES empresas (id);
ALTER TABLE empresas_detalhes ADD CONSTRAINT FK_4D495A466B253812 FOREIGN KEY (detalhe_id) REFERENCES detalhes (id);
ALTER TABLE paginas ADD CONSTRAINT FK_28335C341137ABCF FOREIGN KEY (album_id) REFERENCES albuns (id);
ALTER TABLE imagens ADD CONSTRAINT FK_49E534EF1137ABCF FOREIGN KEY (album_id) REFERENCES albuns (id);
ALTER TABLE produtos ADD CONSTRAINT FK_3E524351137ABCF FOREIGN KEY (album_id) REFERENCES albuns (id);
ALTER TABLE produtos_detalhes ADD CONSTRAINT FK_DA083948105CFD56 FOREIGN KEY (produto_id) REFERENCES produtos (id);
ALTER TABLE produtos_detalhes ADD CONSTRAINT FK_DA0839486B253812 FOREIGN KEY (detalhe_id) REFERENCES detalhes (id);
ALTER TABLE parceiros ADD CONSTRAINT FK_949C60CC1137ABCF FOREIGN KEY (album_id) REFERENCES albuns (id);

-- usuario/senha admin/admin
INSERT INTO `credenciais` (`login`, `senha`, `email`, `salt`) VALUES
('admin', 'ca89ca8e501c5b84e1cfe0afb097f87b67f852c4ec022a50ceffb79f9a30fd3c66326e7f8e416ebcbe8f33b3b20780e0afb1713a2ae22fc7b8bc5d714c113a56', 'fabricio.santos@bestsmart.com.br', '98a5a84e7cc7472c58f81924b855609cf9b339e1ec889515eee7b815580062b8551e30f3696a25b4a667ee8f403aea6c15c7228c108f32222ea79c738774f80e');


--alter table Empresa
ALTER TABLE empresas ADD facebookPageUrl VARCHAR(255) DEFAULT NULL;